name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: OTP ${{matrix.otp}} / Rust ${{matrix.rust}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [21, 22, 23, 24]
        rust: [stable]

    container:
      image: erlang:${{matrix.otp}}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install Rust ${{matrix.rust}} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          override: true

      - name: Check formatting
        run: rebar3 fmt -c

      - name: Compile
        run: rebar3 compile

      - name: Run dialyzer
        run: rebar3 dialyzer

      - name: Run tests
        run: rebar3 ct -c

      - name: Generate coverage reports
        run: rebar3 covertool generate

      - uses: codecov/codecov-action@v1
        with:
          file: _build/test/covertool/cuckoo_filter.covertool.xml
