name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: OTP ${{matrix.otp}} / Rust ${{matrix.rust}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [25, 26, 27]
        rebar3: [3.24.0]
        rust: [stable]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Erlang OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Install Rust ${{matrix.rust}} toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{matrix.rust}}
          override: true

      - name: Check formatting
        run: rebar3 fmt -c

      - name: Compile
        run: rebar3 compile

      - name: Run dialyzer
        run: rebar3 dialyzer

      - name: Run tests
        run: rebar3 ct -c

      - name: Generate coverage reports
        run: rebar3 covertool generate

      - uses: codecov/codecov-action@v3
        with:
          file: _build/test/covertool/cuckoo_filter.covertool.xml
